In [1]:
import DualwormFunctions as dw
import Observables as obs

%load_ext line_profiler
%load_ext memory_profiler

import RunBasis
import argparse
import StartStates as strst
import numpy as np

import yep

In [2]:
nst = 2;
nsm = 2;
nips = 5;
nrps = 5;
nb = 2;
measperiod = 1;
nt = 32
nh = 61
ncores = 8
nmaxiter = 1
stroutput = "Profiling_nh{0}_nt{1}_nst{2}_nsm{3}_nips{4}_nrps{5}_ncores{6}_nmaxiter{7}_v1(compiled)".format(nh, nt, nst, nsm, nips, nrps, ncores, nmaxiter)


In [3]:
def genArgs():
    parser = argparse.ArgumentParser()
    
    parser.add_argument('-f', type = str)

    parser.add_argument('--L', type = int, default = 12, help = 'Lattice side size')

    # COUPLINGS
    parser.add_argument('--J1', type = float, default = 1,
                        help = 'NN coupling') # nearest-neighbour coupling
    parser.add_argument('--J2', type = float, default = 0,
                        help = '2nd NN coupling') # 2nd NN coupling
    parser.add_argument('--J3', type = float, default = 0,
                        help = '3rd NN coupling') # 3rd NN coupling
    parser.add_argument('--J4', type = float, default = 0.0,
                        help = '4th NN coupling')
    parser.add_argument('--h', type = float, default = 1.0,
                        help = 'Magnetic field')    
    #NUMBER OF STEPS AND ITERATIONS
    parser.add_argument('--nst', type = int, default = nst,
                        help = 'number of thermalisation steps') # number of thermalisation steps
    parser.add_argument('--nsm', type = int, default = nsm,
                        help = 'number of measurements steps') # number of measurement steps
    parser.add_argument('--nips', type = int, default = nips,
                        help = 'number of worm constructions per MC step')
    parser.add_argument('--nrps', type = int, default = nrps,
                        help = 'number of replica loops per MC step')
    parser.add_argument('--measperiod', type = int, default = measperiod,
                        help = 'number of nips worm building + swaps between measurements')
    parser.add_argument('--nb', type = int, default = nb,
                        help = 'number of bins')

    #PARALLELISATION
    parser.add_argument('--ncores', type = int, default = ncores,
                        help = 'number of threads to use')

    
    # INITIALISATION PARAMETERS
    parser.add_argument('--randominit', default = True, action ='store_true',
                        help = 'intialise the states randomly')
    parser.add_argument('--same', default = False, action = 'store_true',
                        help = '''initialise all temperatures with the same
                        state (debug purposes)''')
    parser.add_argument('--magninit', default = False, action = 'store_true',
                        help = '''initialise all the temperature with
                        one of the m=1/3 GS''')
    parser.add_argument('--magnstripes', default = False, action = 'store_true',
                       help = '''initialise all the temperature with
                       m=1/3 stripes''')
    parser.add_argument('--maxflip', default = False, action = 'store_true',
                       help = '''initialise all the temperature with
                       maximally flippable plateau''')
    parser.add_argument('--loadfromfile', default = False, action = 'store_true',
                       help = '''initialise all the states with
                       results from a previously performed simulations''')
    parser.add_argument('--filename', type = str, default = 'LongerTests_folder',
                       help = '''initialise all the states with
                       results from a previously performed simulations''')
    
    #WORM PARAMETERS
    parser.add_argument('--nmaxiter', type = int, default = nmaxiter,
                        help = '''maximal number of segments in a loop update over the
                        size of the lattice (1 = 1times the number of dualbonds in the
                        lattice)''')
    parser.add_argument('--measupdate', default = False, action = 'store_true',
                       help = '''activate to mimic the action of the measuring tip''')
    parser.add_argument('--p', type = float, default = 0.0, 
                       help = '''prob of the measuring tip flipping the spin (number between 0 and 1)''')
    parser.add_argument('--ssf', default = True, action = 'store_true',
                        help = 'activate for single spin flip update')
    parser.add_argument('--alternate', default = True, action = 'store_true',
                        help = 'activate for single spin flip update and dw update')
    parser.add_argument('--checkgs', default =False, action = 'store_true',
                        help = 'activate to debug ssf')
    
    #TEMPERATURE PARAMETERS
    parser.add_argument('--t_list', nargs = '+', type = float, default = [0.05,nt+0.05],
                        help = 'list of limiting temperature values')
    parser.add_argument('--nt_list', nargs = '+', type = int, default = [nt],
                        help = 'list of number of temperatures in between the given limiting temperatures')
    parser.add_argument('--log_tlist', default = True, action='store_true',
                        help = 'state whether you want the temperature be spaced log-like or linear-like (activate if you want log)')
    parser.add_argument('--stat_temps_lims', nargs = '+', type = float,
                        help = '''limiting temperatures for the various ranges of
                        measurements''') 
                        #default will be set to none, and then we can decide what to do later on.
    #MAGNETIC FIELD PARAMETERS
    parser.add_argument('--h_list', nargs = '+', default = [0,6.0],type = float,
                        help = 'list of limiting magnetic field values')
    parser.add_argument('--nh_list', nargs = '+', default = [nh], type = int,
                        help = 'list of number of magnetic fields in between the given limiting temperatures')
    parser.add_argument('--stat_hfields_lims', nargs = '+', type = float,
                help = '''limiting magnetic fields for the various ranges of
                measurements''') 
    #CORRELATIONS PARAMETER
    parser.add_argument('--energy', default = True, action = 'store_true',
                        help = 'activate if you want to save the energy')
    parser.add_argument('--magnetisation', default =True, action = 'store_true',
                        help = 'activate if you want to save the magnetisation')
    parser.add_argument('--charges', default = False, action = 'store_true',
                        help = 'activate if you want to save the charges')
    parser.add_argument('--correlations', default = True, action = 'store_true',
                        help = 'activate if you want to save either central or all correlations')
    parser.add_argument('--all_correlations', default = False, action = 'store_true',
                        help = '''activate if you want to save the correlations for all non-equivalent
                        pairs of sites. Otherwise, will save central correlations.''')
    parser.add_argument('--firstcorrelations', default = False, action = 'store_true',
                        help = 'activate if you want to save first correlations, otherwise will save central')
    #SAVE
    parser.add_argument('--output', type = str, default = stroutput, help = 'saving filename (.pkl will be added)')
    args = parser.parse_args()
    return args

In [4]:
def callRunBasis():
    args = genArgs()
    return RunBasis.main(args)

In [5]:
#%%prun -s  -T prun0
yep.start(stroutput+'.log')
%lprun -f dw.mcs_swaps [meanstat, swapst, swapsh, failedupdatesth, failedupdates] = callRunBasis()
yep.stop()

-------------------Initialisation--------------------
./Profiling_nh61_nt32_nst2_nsm2_nips5_nrps5_ncores8_nmaxiter1_v1(compiled)_folder/backup.hkl
Lattice side size:  12
J1  1
J2  0
J3  0
J3st  0
Couplings extracted
Hamiltonian expression (without field) computed
single spin flip update
alternating ssf and dw update
Number of temperatures:  32
Temperatures: [ 0.05        0.06159051  0.07586782  0.09345476  0.11511853  0.14180418
  0.17467584  0.21516749  0.26504552  0.32648578  0.40216853  0.4953953
  0.61023301  0.75169126  0.92594099  1.14058358  1.40498253  1.73067185
  2.1318593   2.6260461   3.23479045  3.98464798  4.90833015  6.04613131
  7.44768641  9.17413633 11.300795   13.92043492 17.14733417 21.1222617
 26.01861809 32.05      ]
Number of magnetic fields:  61
Magnetic fields:  [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9

In [6]:
print(failedupdatesth/(nst*nips))

[[0.56095679 0.95277778 0.98703704 ... 0.95069444 0.95169753 0.95092593]
 [0.55408951 0.93024691 0.96782407 ... 0.95115741 0.95015432 0.95084877]
 [0.55378086 0.90416667 0.96458333 ... 0.94868827 0.95061728 0.95208333]
 ...
 [0.06566358 0.07646605 0.07199074 ... 0.2320216  0.23310185 0.23140432]
 [0.05563272 0.05864198 0.05817901 ... 0.19459877 0.20262346 0.20408951]
 [0.04521605 0.04722222 0.04953704 ... 0.16057099 0.16689815 0.16967593]]


In [7]:
print(failedupdates/(nsm*measperiod*nips))

[[0.55347222 0.9820216  0.99992284 ... 1.00015432 1.00015432 1.00015432]
 [0.5507716  0.95671296 0.99783951 ... 1.00015432 1.00015432 1.00015432]
 [0.54807099 0.93364198 0.99405864 ... 1.00015432 1.00015432 1.00015432]
 ...
 [0.07052469 0.07600309 0.07237654 ... 0.22716049 0.2308642  0.23333333]
 [0.05470679 0.05601852 0.0595679  ... 0.18973765 0.19344136 0.19158951]
 [0.04652778 0.05069444 0.04976852 ... 0.16365741 0.16527778 0.15439815]]


In [8]:
print(4*swapst/(nrps*nsm*measperiod*nh))

[0.74098361 0.60327869 0.85245902 0.68196721 0.8        0.67540984
 0.72131148 0.59672131 0.63606557 0.47213115 0.4852459  0.30163934
 0.15081967 0.01967213 0.07868852 0.01967213 0.05901639 0.02622951
 0.0852459  0.03934426 0.13114754 0.09180328 0.17704918 0.17704918
 0.26229508 0.30819672 0.39344262 0.3147541  0.57704918 0.45901639
 0.69508197 0.        ]


In [9]:
print(4*swapsh/(nrps*nsm*measperiod*nt))

[0.3375 0.425  0.3375 0.6375 0.4    0.775  0.525  0.7625 0.4375 0.8375
 0.4875 0.7875 0.4375 0.6625 0.4375 0.7125 0.375  0.55   0.35   0.5375
 0.4    0.5375 0.4    0.5375 0.3375 0.675  0.4    0.725  0.5    0.8625
 0.5125 0.8875 0.5375 0.875  0.4125 0.7875 0.45   0.625  0.35   0.475
 0.2125 0.5125 0.3625 0.5    0.425  0.7125 0.55   0.625  0.5875 0.8125
 0.5375 0.85   0.65   0.9125 0.675  0.925  0.625  1.     0.65   1.0375
 0.    ]
