In [1]:
import os,sys,inspect
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parentdir = os.path.dirname(currentdir)
sys.path.insert(0,parentdir)

In [2]:
import StartStates as strst
import numpy as np

import AnalysisFunctions as af # functions to make the analysis code cleaner
import KagomeDrawing as kdraw
import DualwormFunctions as dw

import matplotlib.pyplot as plt
%matplotlib inline

import hickle as hkl
import MFUPreparation as mfu

In [3]:
type = 'Inter'

In [4]:
# Create a folder to save the pictures
#stroutputs = ["JustSomeJ11J20.2J30.15_L12_family_I1",
#             "JustSomeJ11J20.2J30.15_L12_family_I2",
#             "JustSomeJ11J20.2J30.15_L12_family_I3"]
#

if type == 'J1J2':
    stroutputs = ["J1J2_J11J20.2J30_L12_family_1",
                  "J1J2_J11J20.2J30_L12_family_2","J1J2_J11J20.2J30_L12_family_3",
                  "J1J2_J11J20.2J30_L12_family_4"]
elif type =='J1J3':
    stroutputs = ["../../Analysis_MFUs/Runs_15-04-20_J1J3MFU/J1J3MFU_L28_nst256_round1/J1J3MFU_L28_nst256_round1",
                  "../../Analysis_MFUs/Runs_15-04-20_J1J3MFU/J1J3MFU_L28_nst256_round2/J1J3MFU_L28_nst256_round2",
                  "../../Analysis_MFUs/Runs_15-04-20_J1J3MFU/J1J3MFU_L28_nst256_round3/J1J3MFU_L28_nst256_round3",
                  "../../Analysis_MFUs/Runs_15-04-20_J1J3MFU/J1J3MFU_L28_nst256_round4/J1J3MFU_L28_nst256_round4"]
elif type =='LargeJ3':
    #stroutputs = ["LargeJ3_J11J20.1J30.2_L16_family_1",
    #              "LargeJ3_J11J20.1J30.2_L16_family_2",
    #              "LargeJ3_J11J20.1J30.2_L16_family_3",
    #              "LargeJ3_J11J20.1J30.2_L16_family_4",
    #              "LargeJ3_J11J20.1J30.2_L16_family_5",
    #              "LargeJ3_J11J20.1J30.2_L16_family_6",
    #              "LargeJ3_J11J20.1J30.2_L16_family_7",
    #              "LargeJ3_J11J20.1J30.2_L16_family_8",
    #              "LargeJ3_J11J20.1J30.2_L16_family_9"]
    # stroutputs = ["../../Analysis_MFUs/Runs_17-04-20_LargeJ3NotRandomMFU/LargeJ3NRMFU_L32_nst512_round1/LargeJ3NRMFU_L32_nst512_round1",
    #               "../../Analysis_MFUs/Runs_17-04-20_LargeJ3NotRandomMFU/LargeJ3NRMFU_L32_nst512_round2/LargeJ3NRMFU_L32_nst512_round2",
    #               "../../Analysis_MFUs/Runs_17-04-20_LargeJ3NotRandomMFU/LargeJ3NRMFU_L32_nst512_round3/LargeJ3NRMFU_L32_nst512_round3",
    #               "../../Analysis_MFUs/Runs_17-04-20_LargeJ3NotRandomMFU/LargeJ3NRMFU_L32_nst512_round4/LargeJ3NRMFU_L32_nst512_round4",
    #               "../../Analysis_MFUs/Runs_17-04-20_LargeJ3NotRandomMFU/LargeJ3NRMFU_L32_nst512_round10/LargeJ3NRMFU_L32_nst512_round10"]
    stroutputs = ["../../Analysis_MFUs/Runs_15-04-20_LargeJ3MFU/LargeJ3MFU_L24_nst131072_round1/LargeJ3MFU_L24_nst131072_round1",
                  "../../Analysis_MFUs/Runs_15-04-20_LargeJ3MFU/LargeJ3MFU_L24_nst131072_round2/LargeJ3MFU_L24_nst131072_round2",
                  "../../Analysis_MFUs/Runs_15-04-20_LargeJ3MFU/LargeJ3MFU_L24_nst131072_round3/LargeJ3MFU_L24_nst131072_round3",
                  "../../Analysis_MFUs/Runs_15-04-20_LargeJ3MFU/LargeJ3MFU_L24_nst131072_round4/LargeJ3MFU_L24_nst131072_round4",
                  "../../Analysis_MFUs/Runs_15-04-20_LargeJ3MFU/LargeJ3MFU_L24_nst131072_round5/LargeJ3MFU_L24_nst131072_round5",
                  "../../Analysis_MFUs/Runs_15-04-20_LargeJ3MFU/LargeJ3MFU_L24_nst131072_round6/LargeJ3MFU_L24_nst131072_round6",
                  "../../Analysis_MFUs/Runs_15-04-20_LargeJ3MFU/LargeJ3MFU_L24_nst131072_round7/LargeJ3MFU_L24_nst131072_round7",
                  "../../Analysis_MFUs/Runs_15-04-20_LargeJ3MFU/LargeJ3MFU_L24_nst131072_round8/LargeJ3MFU_L24_nst131072_round8",
                  "../../Analysis_MFUs/Runs_15-04-20_LargeJ3MFU/LargeJ3MFU_L24_nst131072_round9/LargeJ3MFU_L24_nst131072_round9",
                  "../../Analysis_MFUs/Runs_15-04-20_LargeJ3MFU/LargeJ3MFU_L24_nst131072_round10/LargeJ3MFU_L24_nst131072_round10"]
elif type =='LargeJ2':
    stroutputs = ["LargeJ2_J11J20.2J30.05_L12_family_1",
                  "LargeJ2_J11J20.2J30.05_L12_family_2",
                  "LargeJ2_J11J20.2J30.05_L12_family_3",
                  "LargeJ2_J11J20.2J30.05_L12_family_4",
                  "LargeJ2_J11J20.2J30.05_L12_family_5",
                  "LargeJ2_J11J20.2J30.05_L12_family_6",
                  "LargeJ2_J11J20.2J30.05_L12_family_7",
                  "LargeJ2_J11J20.2J30.05_L12_family_8",
                  "LargeJ2_J11J20.2J30.05_L12_family_9",
                  "LargeJ2_J11J20.2J30.05_L12_family_10",
                  "LargeJ2_J11J20.2J30.05_L12_family_11"]
elif type == 'Inter':
    stroutputs = ["../../Analysis_MFUs/Runs_16-04-20_InterNotRandomMFU/InterMFU_L24_nst512_round1/InterMFU_L24_nst512_round1",
                 "../../Analysis_MFUs/Runs_16-04-20_InterNotRandomMFU/InterMFU_L24_nst512_round2/InterMFU_L24_nst512_round2",
                 "../../Analysis_MFUs/Runs_16-04-20_InterNotRandomMFU/InterMFU_L24_nst512_round3/InterMFU_L24_nst512_round3",
                 "../../Analysis_MFUs/Runs_16-04-20_InterNotRandomMFU/InterMFU_L24_nst512_round4/InterMFU_L24_nst512_round4",
                  "../../Analysis_MFUs/Runs_16-04-20_InterNotRandomMFU/InterMFU_L24_nst512_round5/InterMFU_L24_nst512_round5",
                 "../../Analysis_MFUs/Runs_16-04-20_InterNotRandomMFU/InterMFU_L24_nst512_round6/InterMFU_L24_nst512_round6",
                 "../../Analysis_MFUs/Runs_16-04-20_InterNotRandomMFU/InterMFU_L24_nst512_round7/InterMFU_L24_nst512_round7",
                 "../../Analysis_MFUs/Runs_16-04-20_InterNotRandomMFU/InterMFU_L24_nst512_round8/InterMFU_L24_nst512_round8",
                 "../../Analysis_MFUs/Runs_16-04-20_InterNotRandomMFU/InterMFU_L24_nst512_round9/InterMFU_L24_nst512_round9",
                 "../../Analysis_MFUs/Runs_16-04-20_InterNotRandomMFU/InterMFU_L24_nst512_round10/InterMFU_L24_nst512_round10",
                 "../../Analysis_MFUs/Runs_15-04-20_InterMFU/InterMFU_c4_L24_nst32768_round2/InterMFU_c4_L24_nst32768_round2",
                 "../../Analysis_MFUs/Runs_15-04-20_InterMFU/InterMFU_c4_L24_nst32768_round3/InterMFU_c4_L24_nst32768_round3",
                 "../../Analysis_MFUs/Runs_15-04-20_InterMFU/InterMFU_c4_L24_nst32768_round4/InterMFU_c4_L24_nst32768_round4",
                 "../../Analysis_MFUs/Runs_15-04-20_InterMFU/InterMFU_c3_L24_nst32768_round5/InterMFU_c3_L24_nst32768_round5",
                 "../../Analysis_MFUs/Runs_15-04-20_InterMFU/InterMFU_c4_L24_nst32768_round6/InterMFU_c4_L24_nst32768_round6",
                 "../../Analysis_MFUs/Runs_15-04-20_InterMFU/InterMFU_c3_L24_nst32768_round7/InterMFU_c3_L24_nst32768_round7",
                 "../../Analysis_MFUs/Runs_15-04-20_InterMFU/InterMFU_c3_L24_nst32768_round8/InterMFU_c3_L24_nst32768_round8",
                 "../../Analysis_MFUs/Runs_15-04-20_InterMFU/InterMFU_c4_L24_nst32768_round9/InterMFU_c4_L24_nst32768_round9",
                 "../../Analysis_MFUs/Runs_15-04-20_InterMFU/InterMFU_c4_L24_nst32768_round10/InterMFU_c4_L24_nst32768_round10"]
    
    
    #stroutputs = ["../../Analysis_MFUs/Runs_15-04-20_InterMFU/InterMFU_L12_nst131072_round2/InterMFU_L12_nst131072_round2",
    #             "../../Analysis_MFUs/Runs_15-04-20_InterMFU/InterMFU_L12_nst131072_round3/InterMFU_L12_nst131072_round3",
    #             "../../Analysis_MFUs/Runs_15-04-20_InterMFU/InterMFU_L12_nst131072_round4/InterMFU_L12_nst131072_round4",
    #             "../../Analysis_MFUs/Runs_15-04-20_InterMFU/InterMFU_L12_nst131072_round5/InterMFU_L12_nst131072_round5",
    #             "../../Analysis_MFUs/Runs_15-04-20_InterMFU/InterMFU_L12_nst131072_round6/InterMFU_L12_nst131072_round6",
    #             "../../Analysis_MFUs/Runs_15-04-20_InterMFU/InterMFU_L12_nst131072_round7/InterMFU_L12_nst131072_round7",
    #             "../../Analysis_MFUs/Runs_15-04-20_InterMFU/InterMFU_L12_nst131072_round8/InterMFU_L12_nst131072_round8",
    #             "../../Analysis_MFUs/Runs_15-04-20_InterMFU/InterMFU_L12_nst131072_round9/InterMFU_L12_nst131072_round9",
    #             "../../Analysis_MFUs/Runs_15-04-20_InterMFU/InterMFU_L12_nst131072_round10/InterMFU_L12_nst131072_round10"]
                        
elif type == 'Phase2':
    stroutputs = ["Phase2_J10.5J20.5J3-1_L8_1",
                  "Phase2_J10.5J20.5J3-1_L8_2",
                  "Phase2_J10.5J20.5J3-1_L8_3",
                  "Phase2_J10.5J20.5J3-1_L8_4"]
elif type == 'Phase5':
    stroutputs = ["Phase5_J11J2-1J31_L8_1"]
elif type == 'Phase8':    
    #stroutputs = ["Phase8_J1-0.2J21J31_L8_1",
    #              "Phase8_J1-0.2J21J31_L8_2",
    #              "Phase8_J1-0.2J21J31_L8_3",
    #              "Phase8_J1-0.2J21J31_L8_4",
    #              "Phase8_J1-0.2J21J31_L8_5",
    #              "Phase8_J1-0.2J21J31_L8_6",
    #              "Phase8_J1-0.2J21J31_L8_7",
    #              "Phase8_J1-0.2J21J31_L8_8",
    #              "Phase8_J1-0.2J21J31_L8_9",
    #              "Phase8_J1-0.2J21J31_L8_10",
    #              "Phase8_J1-0.2J21J31_L8_11",
    #              "Phase8_J1-0.2J21J31_L8_12",
    #              "Phase8_J1-0.2J21J31_L8_13",
    #              "Phase8_J1-0.2J21J31_L8_14",
    #              "Phase8_J1-0.2J21J31_L8_15",
    #              "Phase8_J1-0.2J21J31_L8_16",
    #              "Phase8_J1-0.2J21J31_L8_17",
    #              "Phase8_J1-0.2J21J31_L8_18",
    #              "Phase8_J1-0.2J21J31_L8_19",
    #              "Phase8_J1-0.2J21J31_L8_20",
    #              "Phase8_J1-0.2J21J31_L8_21",
    #              "Phase8_J1-0.2J21J31_L8_22",
    #              "Phase8_J1-0.2J21J31_L8_23",
    #              "Phase8_J1-0.2J21J31_L8_24"]
    stroutputs = ["../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round1/Phase8MFU_c1_L12_nst1024_round1",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round2/Phase8MFU_c1_L12_nst1024_round2",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round3/Phase8MFU_c1_L12_nst1024_round3",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round4/Phase8MFU_c1_L12_nst1024_round4",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round5/Phase8MFU_c1_L12_nst1024_round5",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round6/Phase8MFU_c1_L12_nst1024_round6",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round7/Phase8MFU_c1_L12_nst1024_round7",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round8/Phase8MFU_c1_L12_nst1024_round8",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round9/Phase8MFU_c1_L12_nst1024_round9",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round10/Phase8MFU_c1_L12_nst1024_round10",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round11/Phase8MFU_c1_L12_nst1024_round11",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round12/Phase8MFU_c1_L12_nst1024_round12",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round13/Phase8MFU_c1_L12_nst1024_round13",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round14/Phase8MFU_c1_L12_nst1024_round14",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round15/Phase8MFU_c1_L12_nst1024_round15",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round16/Phase8MFU_c1_L12_nst1024_round16",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round17/Phase8MFU_c1_L12_nst1024_round17",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round18/Phase8MFU_c1_L12_nst1024_round18",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round19/Phase8MFU_c1_L12_nst1024_round19",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round20/Phase8MFU_c1_L12_nst1024_round20",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round21/Phase8MFU_c1_L12_nst1024_round21",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round22/Phase8MFU_c1_L12_nst1024_round22",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round23/Phase8MFU_c1_L12_nst1024_round23",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round24/Phase8MFU_c1_L12_nst1024_round24",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round25/Phase8MFU_c1_L12_nst1024_round25",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round26/Phase8MFU_c1_L12_nst1024_round26",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round27/Phase8MFU_c1_L12_nst1024_round27",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round28/Phase8MFU_c1_L12_nst1024_round28",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round29/Phase8MFU_c1_L12_nst1024_round29",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round30/Phase8MFU_c1_L12_nst1024_round30",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round31/Phase8MFU_c1_L12_nst1024_round31",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round32/Phase8MFU_c1_L12_nst1024_round32",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round33/Phase8MFU_c1_L12_nst1024_round33",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round34/Phase8MFU_c1_L12_nst1024_round34",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round35/Phase8MFU_c1_L12_nst1024_round35",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round36/Phase8MFU_c1_L12_nst1024_round36",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round37/Phase8MFU_c1_L12_nst1024_round37",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round38/Phase8MFU_c1_L12_nst1024_round38",
                 "../../Analysis_MFUs/Runs_20-04-20_Phase8/Phase8MFU_c1_L12_nst1024_round39/Phase8MFU_c1_L12_nst1024_round39",
                 "Phase8_J1-0.2J21J31_L12_1"]
elif type == 'Phase9':
    stroutputs = ["Phase9_J1-1J21J3-0.3_L4_1",
                  "Phase9_J1-1J21J3-0.3_L4_2",
                  "Phase9_J1-1J21J3-0.3_L4_3",
                  "Phase9_J1-1J21J3-0.3_L4_4",
                  "Phase9_J1-1J21J3-0.3_L4_5",
                  "Phase9_J1-1J21J3-0.3_L4_6"]
elif type == 'Phase11':
    stroutputs = ["Phase11_J1-1J2-1J3-1_L4_1","Phase11_J1-1J2-1J3-1_L4_2"]
    
nsm =64
foldernames = ["./" + stroutput+ "_folder/" for stroutput in stroutputs]
results_foldername = 'Results/'

#os.makedirs('IntermediateFamilyStates3/' + results_foldername, exist_ok = True)
#results_foldername = 'IntermediateFamilyStates3/' + results_foldername

if type == 'J1J2':
    os.makedirs('J1J2Families/' + results_foldername, exist_ok = True)
    results_foldername = 'J1J2Families/' + results_foldername
elif type == 'J1J3':
    os.makedirs('J1J3FamiliesCluster/' + results_foldername, exist_ok = True)
    results_foldername = 'J1J3FamiliesCluster/' + results_foldername
elif type == 'LargeJ3':
    os.makedirs('LargeJ3FamiliesR/' + results_foldername, exist_ok = True)
    results_foldername = 'LargeJ3FamiliesR/' + results_foldername
elif type == 'LargeJ2':
    os.makedirs('LargeJ2Families/' + results_foldername, exist_ok = True)
    results_foldername = 'LargeJ2Families/' + results_foldername    
elif type == 'Inter':
    os.makedirs('InterFamilies_24_R+NR/' + results_foldername, exist_ok = True)
    results_foldername = 'InterFamilies_24_R+NR/' + results_foldername   
elif type == 'Phase2':
    os.makedirs('Phase2Families/' + results_foldername, exist_ok = True)
    results_foldername = 'Phase2Families/' + results_foldername  
elif type == 'Phase5':
    os.makedirs('Phase5Families/' + results_foldername, exist_ok = True)
    results_foldername = 'Phase5Families/' + results_foldername
elif type == 'Phase8':
    os.makedirs('Phase8Families_Clusters/' + results_foldername, exist_ok = True)
    results_foldername = 'Phase8Families_Clusters/' + results_foldername  
elif type == 'Phase9':
    os.makedirs('Phase9Families/' + results_foldername, exist_ok = True)
    results_foldername = 'Phase9Families/' + results_foldername  
elif type == 'Phase11':
    os.makedirs('Phase11Families/' + results_foldername, exist_ok = True)
    results_foldername = 'Phase11Families/' + results_foldername       

filenamelist = ["backup"]

[L, numsites, J1, J2, J3, J3st, J4, nb, num_in_bin, temperatures, nt,
 stat_temps, temperatures_plots, hfields, nh,
 stat_hfields, hfields_plots, listfunctions, sref] =\
af.LoadParameters(foldernames[0], filenamelist)



In [5]:
kw = {'binning': False, 'plzplot': True, 'plotmin': 0, 'plotmax': 16}

[groundspinstates, groundstates, groundcharges] = \
 af.LoadGroundStates(foldernames[0], filenamelist, L, nh, [nsm],**kw)

groundspinstates = groundspinstates[0]
groundstates = groundstates[0]
groundcharges = groundcharges[0]

for i in range(1,len(foldernames)):
    [gsps, gs, gc] = \
     af.LoadGroundStates(foldernames[i], filenamelist, L, nh, [nsm],**kw)
    groundspinstates = np.concatenate((groundspinstates, gsps[0]))
    groundstates = np.concatenate((groundstates, gs[0]))
    groundcharges = np.concatenate((groundcharges, gc[0]))
    
[d_ijl, ijl_d, s_ijl, ijl_s, d_2s, s2_d, d_nd, d_vd, d_wn,
 sidlist, didlist, c_ijl, ijl_c, c2s, csign] =\
dw.latticeinit(L[0])
(s_ijl, ijl_s) = kdraw.createspinsitetable(L[0])


backup = "./"+foldernames[0]+filenamelist[0]+".hkl"
couplings = hkl.load(backup, path="/parameters/couplings")
hamiltonian = dw.Hamiltonian(couplings, d_ijl, ijl_d, L[0])

if type == 'J1J2':
    gsenergy = -2/3 * J1[0] - 2/3 * J2[0]
elif type == 'J1J3':
    gsenergy = -2/3 * J1[0] -  J3[0]
elif type == 'Inter':
    gsenergy = -2/3 * J1[0] - 1/3 * J3[0]
elif type == 'LargeJ3':
    gsenergy = -2/3 * J1[0] + 2/3 * J2[0] -  J3[0]
elif type == 'LargeJ2':
    gsenergy = -2/3 * J1[0] - 2/3 * J2[0] +  J3[0]
elif type == 'Phase2':
    gsenergy = -2/3 * J1[0] - 2/3 * J2[0] +  3*J3[0]
elif type == 'Phase5':
    gsenergy = -2/3 * J1[0] + 2 * J2[0] - J3[0]
elif type == 'Phase8':
    gsenergy = 2/3 * J1[0] - (2/3) * J2[0] - J3[0]
elif type == 'Phase9':
    gsenergy = 2/3 * J1[0] - (2/3) * J2[0] + (1/3)*J3[0]
elif type == 'Phase11':
    gsenergy = 2 * J1[0] + 2 * J2[0] +3 * J3[0]
latsize = len(s_ijl)
families, spinfamilies = mfu.FamiliesFromStates(hamiltonian, groundstates,
                                      gsenergy, groundspinstates,
                                      d_wn, latsize, 0.5, d_ijl)

stateid =  0
stateid =  1
stateid =  2
stateid =  3
stateid =  4
stateid =  5
stateid =  6
stateid =  7
stateid =  8
stateid =  9
stateid =  10
stateid =  11
stateid =  12
stateid =  13
stateid =  14
stateid =  15
stateid =  16
stateid =  17
stateid =  18
stateid =  19
stateid =  20
stateid =  21
stateid =  22
stateid =  23
stateid =  24
stateid =  25
stateid =  26
stateid =  27
stateid =  28
stateid =  29
stateid =  30
stateid =  31
stateid =  32
stateid =  33
stateid =  34
stateid =  35
stateid =  36
stateid =  37
stateid =  38
stateid =  39
stateid =  40
stateid =  41
stateid =  42
stateid =  43
stateid =  44
stateid =  45
stateid =  46
stateid =  47
stateid =  48
stateid =  49
stateid =  50
stateid =  51
stateid =  52
stateid =  53
stateid =  54
stateid =  55
stateid =  56
stateid =  57
stateid =  58
stateid =  59
stateid =  60
stateid =  61
stateid =  62
stateid =  63
stateid =  64
stateid =  65
stateid =  66
stateid =  67
stateid =  68
stateid =  69
stateid =  70
stateid =  71
st

In [6]:
xmin = L[0]-2
xmax = 3*L[0]-3
ymin = L[0]-2
ymax = 3*L[0]-3

In [7]:
xmin2 = 2*L[0]+2
xmax2 = 4*L[0]+1
ymin2 = 2*L[0]+2
ymax2 = 4*L[0]+1

In [8]:
ymax

69

In [9]:
families

[[0,
  129,
  131,
  133,
  135,
  137,
  139,
  141,
  143,
  145,
  147,
  149,
  151,
  153,
  155,
  157,
  159,
  161,
  163,
  165,
  167,
  169,
  171,
  173,
  175,
  177,
  179,
  181,
  183,
  185,
  187,
  189,
  191,
  320,
  322,
  324,
  326,
  328,
  330,
  332,
  334,
  336,
  338,
  340,
  342,
  344,
  346,
  348,
  350,
  352,
  354,
  356,
  358,
  360,
  362,
  364,
  366,
  368,
  370,
  372,
  374,
  376,
  378,
  380,
  382],
 [1,
  321,
  323,
  325,
  327,
  329,
  331,
  333,
  335,
  337,
  339,
  341,
  343,
  345,
  347,
  349,
  351,
  353,
  355,
  357,
  359,
  361,
  363,
  365,
  367,
  369,
  371,
  373,
  375,
  377,
  379,
  381,
  383,
  512,
  514,
  516,
  518,
  520,
  522,
  524,
  526,
  528,
  530,
  532,
  534,
  536,
  538,
  540,
  542,
  544,
  546,
  548,
  550,
  552,
  554,
  556,
  558,
  560,
  562,
  564,
  566,
  568,
  570,
  572,
  574],
 [64,
  449,
  451,
  453,
  455,
  457,
  459,
  461,
  463,
  465,
  467,
  469,
  471,
  

In [12]:
color_c1 = "pink"
color_c2 = "lightgreen"
color_c3 = "lightblue"
color_c4 = "orange"
i = 0
for idfam, family in enumerate(families):
    currentfolder =results_foldername+'Family{0}/'.format(idfam)  
    os.makedirs(currentfolder, exist_ok = True)
    for idstate, index in enumerate(family):
        
        #plot the state:
        #kdraw.plotstate(index, L[0], d_ijl, ijl_s, sidlist, didlist, s2_d,
        #           groundstates, groundspinstates,dim_node_color = 'peachpuff',
        #            dim_color = "peachpuff", no_dim_color = 'lightgrey')
        #kdraw.plot_honeycomb_chargestate(groundcharges[index], ijl_c, L[0],
        #                                 2, c1_color = color_c1, 
        #                                 c2_color = color_c2,
        #                                 c3_color = color_c3,
        #                                 c4_color = color_c4)
        #plt.tick_params(  
        #    which = 'both',      # both major and minor ticks are affected
        #    bottom = False,      # ticks along the bottom edge are off
        #    top = False,         # ticks along the top edge are off
        #    labelbottom = False,
        #    left = False,
        #    right = False,
        #    labelleft = False)
        #plt.legend()
        ##plt.savefig(results_foldername + 'Family{0}/GroundState_index{1}.png'.format(idfam, idstate))
        #plt.show()
        
        # save the spin state
        np.savetxt(currentfolder+"spinstate{0}.txt".format(idstate*2), groundspinstates[index])
        # save - the spin state
        np.savetxt(currentfolder+"spinstate{0}.txt".format(idstate*2+1), -groundspinstates[index])
    
        # save the matrix form
        m = mfu.mapStateToMatrix(L[0],s_ijl, groundspinstates[index])
        print(m[xmin2:xmax2,ymin2:xmax2])
        np.savetxt(currentfolder+"matrix_spinstate{0}.txt".format(idstate*4), m[xmin:xmax,ymin:ymax])
        np.savetxt(currentfolder+"matrix_spinstate{0}.txt".format(idstate*4+1), -m[xmin:xmax,ymin:ymax])
        np.savetxt(currentfolder+"matrix_spinstate{0}.txt".format(idstate*4+2), m[xmin2:xmax2,ymin2:ymax2])
        np.savetxt(currentfolder+"matrix_spinstate{0}.txt".format(idstate*4+3), -m[xmin2:xmax2,ymin2:ymax2])
        
        



[[ 1  1 -1 ...  1 -1  1]
 [-1  0 -1 ...  1  0 -1]
 [ 1  1 -1 ... -1  1 -1]
 ...
 [ 1 -1  1 ...  1 -1 -1]
 [ 1  0 -1 ...  1  0  1]
 [-1  1 -1 ...  1 -1 -1]]
[[ 1  1 -1 ...  1 -1  1]
 [-1  0 -1 ...  1  0 -1]
 [ 1  1 -1 ... -1  1 -1]
 ...
 [ 1  1  1 ...  1 -1 -1]
 [-1  0 -1 ...  1  0  1]
 [-1  1 -1 ...  1 -1 -1]]
[[ 1  1 -1 ...  1 -1  1]
 [-1  0 -1 ...  1  0 -1]
 [ 1  1 -1 ... -1  1 -1]
 ...
 [ 1  1  1 ...  1 -1 -1]
 [-1  0 -1 ...  1  0  1]
 [-1  1 -1 ...  1 -1 -1]]
[[ 1  1 -1 ...  1 -1  1]
 [-1  0 -1 ...  1  0 -1]
 [ 1  1 -1 ... -1  1 -1]
 ...
 [ 1  1  1 ...  1 -1 -1]
 [-1  0 -1 ...  1  0  1]
 [-1  1 -1 ...  1 -1 -1]]
[[ 1  1 -1 ...  1 -1  1]
 [-1  0 -1 ...  1  0 -1]
 [ 1  1 -1 ... -1  1 -1]
 ...
 [ 1  1  1 ...  1 -1 -1]
 [-1  0 -1 ...  1  0  1]
 [-1  1 -1 ...  1 -1 -1]]
[[ 1  1 -1 ...  1 -1  1]
 [-1  0 -1 ...  1  0 -1]
 [ 1  1 -1 ... -1  1 -1]
 ...
 [ 1  1  1 ...  1 -1 -1]
 [-1  0 -1 ...  1  0  1]
 [-1  1 -1 ...  1 -1 -1]]
[[ 1  1 -1 ...  1 -1  1]
 [-1  0 -1 ...  1  0 -1]
 [ 1  1 -1 ...

In [13]:
print(len(families))

24
